"""add a few models

Revision ID: 333298b8f0ff
Revises: 535d2f40167e
Create Date: 2024-11-18 20:31:03.791526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '333298b8f0ff'
down_revision: Union[str, None] = '535d2f40167e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_table('hashtags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_hashtags_id'), 'hashtags', ['id'], unique=False)
    op.create_table('publication_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'NOT_FOUND', 'HIDDEN', 'ERROR', name='snapshotstatusenum'), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publication_snapshots_id'), 'publication_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_publication_snapshots_status'), 'publication_snapshots', ['status'], unique=False)
    op.create_table('publications_hashtags',
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.Column('hashtag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], )
    )
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.add_column('cities', sa.Column('id_vk', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    op.drop_column('cities', 'vk_id')
    op.add_column('countries', sa.Column('id_vk', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    op.drop_column('countries', 'vk_id')
    op.add_column('publications', sa.Column('id_vk', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_publications_id'), 'publications', ['id'], unique=False)
    op.drop_column('publications', 'vk_id')
    op.add_column('users', sa.Column('id_vk', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'vk_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vk_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'id_vk')
    op.add_column('publications', sa.Column('vk_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_publications_id'), table_name='publications')
    op.drop_column('publications', 'id_vk')
    op.add_column('countries', sa.Column('vk_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.drop_column('countries', 'id_vk')
    op.add_column('cities', sa.Column('vk_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_cities_id'), table_name='cities')
    op.drop_column('cities', 'id_vk')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_table('publications_hashtags')
    op.drop_index(op.f('ix_publication_snapshots_status'), table_name='publication_snapshots')
    op.drop_index(op.f('ix_publication_snapshots_id'), table_name='publication_snapshots')
    op.drop_table('publication_snapshots')
    op.drop_index(op.f('ix_hashtags_id'), table_name='hashtags')
    op.drop_table('hashtags')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
