"""change unique constraints for publ

Revision ID: b97f73f963d1
Revises: aaa017b6045a
Create Date: 2024-12-01 16:16:01.353020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b97f73f963d1'
down_revision: Union[str, None] = 'aaa017b6045a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('publications_id_vk_key', 'publications', type_='unique')
    op.create_unique_constraint('unique_publ', 'publications', ['id_vk', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_publ', 'publications', type_='unique')
    op.create_unique_constraint('publications_id_vk_key', 'publications', ['id_vk'])
    # ### end Alembic commands ###
